import { rowsToCards } from "./flashcard-types";

const rows = [
  "att tro|to believe, to think|v.|Jag tror att det regnar.",
  "att tänka|to think|v.|Jag tänker på dig.",
  "att känna|to feel, to know (a person)|v.|Jag känner honom väl.",
  "att veta|to know (a fact)|v.|Vet du var hon bor?",
  "att glömma|to forget|v.|Jag glömde nyckeln.",
  "att minnas|to remember|v.|Minns du sommaren?",
  "att bestämma|to decide|v.|Vi bestämde oss igår.",
  "att välja|to choose|v.|Välj vad du vill.",
  "att försöka|to try|v.|Försök igen imorgon.",
  "att lyckas|to succeed|v.|Hon lyckades med provet.",
  "att misslyckas|to fail|v.|Planen misslyckades.",
  "att hända|to happen|v.|Vad hände igår?",
  "att ändra|to change|v.|Vi ändrade planerna.",
  "att fortsätta|to continue|v.|Fortsätt rakt fram.",
  "att sluta|to stop, to quit|v.|Han slutade röka.",
  "att börja|to begin|v.|Kursen börjar i höst.",
  "att bli|to become|v.|Det blir kallt ikväll.",
  "att verka|to seem|v.|Hon verkar trött.",
  "att låta|to sound, to let|v.|Det låter bra.",
  "att räcka|to be enough|v.|Det räcker nu.",
  "att hinna|to have time to|v.|Jag hann inte äta.",
  "att orka|to have the energy to|v.|Jag orkar inte springa.",
  "att våga|to dare|v.|Han vågade inte fråga.",
  "att slippa|to avoid having to|v.|Jag slapp jobba igår.",
  "att undvika|to avoid|v.|Undvik rusningstid.",
  "att märka|to notice|v.|Jag märkte skillnaden.",
  "att tvivla|to doubt|v.|Jag tvivlar på det.",
  "att lova|to promise|v.|Jag lovar att komma.",
  "att erbjuda|to offer|v.|De erbjöd mig jobbet.",
  "att kräva|to demand, to require|v.|Jobbet kräver erfarenhet.",
  "att föreslå|to suggest|v.|Jag föreslår en paus.",
  "att förklara|to explain|v.|Kan du förklara igen?",
  "att beskriva|to describe|v.|Beskriv problemet.",
  "att diskutera|to discuss|v.|Vi diskuterade länge.",
  "att jämföra|to compare|v.|Jämför priserna.",
  "att uppskatta|to appreciate|v.|Jag uppskattar hjälpen.",
  "att tacka|to thank|v.|Jag vill tacka dig.",
  "att sakna|to miss, to lack|v.|Jag saknar dig.",
  "att längta|to long for|v.|Jag längtar efter sommaren.",
  "att hoppas|to hope|v.|Jag hoppas det går bra.",
  "att oroa sig|to worry|v.|Oroa dig inte.",
  "att skynda sig|to hurry|v.|Skynda dig, bussen går!",
  "att vila|to rest|v.|Vila lite nu.",
  "att träna|to exercise, to train|v.|Jag tränar tre gånger i veckan.",
  "att laga|to cook, to repair|v.|Han lagar middag.",
  "att städa|to clean|v.|Jag städar på lördagar.",
  "att tvätta|to wash|v.|Tvätta händerna.",
  "att handla|to shop|v.|Vi handlar på fredagar.",
  "att beställa|to order|v.|Jag beställde en kaffe.",
  "att betala|to pay|v.|Kan jag betala med kort?",
  "att kosta|to cost|v.|Det kostar för mycket.",
  "att spara|to save|v.|Jag sparar till en resa.",
  "att låna|to borrow, to lend|v.|Får jag låna en penna?",
  "att hyra|to rent|v.|Vi hyr en lägenhet.",
  "att flytta|to move|v.|De flyttade till Lund.",
  "att resa|to travel|v.|Vi reser i juli.",
  "att åka|to go (by vehicle)|v.|Vi åker tåg dit.",
  "att landa|to land|v.|Planet landade sent.",
  "att boka|to book|v.|Jag bokade ett rum.",
  "att packa|to pack|v.|Har du packat?",
  "erfarenhet|experience|n.|Hon har lång erfarenhet.",
  "utbildning|education|n.|Min utbildning tog fyra år.",
  "kunskap|knowledge|n.|Kunskap tar tid.",
  "ansökan|application|n.|Jag skickade in ansökan.",
  "möte|meeting|n.|Mötet är flyttat.",
  "beslut|decision|n.|Ett svårt beslut.",
  "förslag|suggestion|n.|Ett bra förslag.",
  "anledning|reason|n.|Vad är anledningen?",
  "orsak|cause|n.|Orsaken är okänd.",
  "resultat|result|n.|Resultatet var bra.",
  "möjlighet|opportunity, possibility|n.|En unik möjlighet.",
  "svårighet|difficulty|n.|Vi hade vissa svårigheter.",
  "problem|problem|n.|Inga problem alls.",
  "lösning|solution|n.|Vi hittade en lösning.",
  "fördel|advantage|n.|En stor fördel.",
  "nackdel|disadvantage|n.|Det finns en nackdel.",
  "skillnad|difference|n.|Det gör stor skillnad.",
  "exempel|example|n.|Till exempel kaffe.",
  "syfte|purpose|n.|Vad är syftet?",
  "mål|goal|n.|Mitt mål är att prata flytande.",
  "krav|requirement|n.|Höga krav på jobbet.",
  "ansvar|responsibility|n.|Det är mitt ansvar.",
  "förmåga|ability|n.|Hon har stor förmåga.",
  "vana|habit|n.|En dålig vana.",
  "känsla|feeling|n.|En underlig känsla.",
  "åsikt|opinion|n.|Vad är din åsikt?",
  "uppfattning|perception, view|n.|Min uppfattning är annan.",
  "intryck|impression|n.|Ett gott intryck.",
  "minne|memory|n.|Ett fint minne.",
  "dröm|dream|n.|En gammal dröm.",
  "förhållande|relationship|n.|Ett långt förhållande.",
  "samhälle|society|n.|Det svenska samhället.",
  "miljö|environment|n.|Bra för miljön.",
  "hälsa|health|n.|Hälsan går först.",
  "sjukdom|illness|n.|En vanlig sjukdom.",
  "behandling|treatment|n.|Behandlingen hjälpte.",
  "myndighet|authority, agency|n.|Kontakta myndigheten.",
  "regering|government|n.|Regeringen beslutade igår.",
  "lag|law|n.|Enligt lagen är det förbjudet.",
  "rättighet|right|n.|Det är din rättighet.",
  "skatt|tax|n.|Skatten är hög.",
  "lön|salary|n.|Lönen betalas den 25:e.",
  "arbetsgivare|employer|n.|Min arbetsgivare är snäll.",
  "kollega|colleague|n.|En trevlig kollega.",
  "chef|boss|n.|Min chef är på semester.",
  "semester|vacation|n.|Jag har semester i juli.",
  "ledighet|time off|n.|Jag tog ledigt en dag.",
  "hyra|rent|n.|Hyran höjs i januari.",
  "räkning|bill, invoice|n.|Räkningen kom idag.",
  "avtal|agreement, contract|n.|Vi skrev på avtalet.",
  "försäkring|insurance|n.|Har du en försäkring?",
  "tillstånd|permit, condition|n.|Du behöver tillstånd.",
  "annars|otherwise|adv.|Skynda, annars missar vi tåget.",
  "dessutom|moreover|adv.|Dessutom är det billigt.",
  "däremot|on the other hand|adv.|Han gillar fisk, jag däremot inte.",
  "därför|therefore|adv.|Därför stannar jag hemma.",
  "eftersom|because|conj.|Eftersom det regnar stannar vi.",
  "trots|despite|prep.|Trots regnet gick vi ut.",
  "trots att|even though|conj.|Trots att hon var trött jobbade hon.",
  "medan|while|conj.|Jag läser medan du sover.",
  "innan|before|conj.|Ring innan du kommer.",
  "efter att|after|conj.|Efter att vi ätit gick vi.",
  "istället|instead|adv.|Ta te istället.",
  "ändå|anyway, still|adv.|Jag gick ändå.",
  "faktiskt|actually|adv.|Det var faktiskt roligt.",
  "verkligen|really|adv.|Det var verkligen bra.",
  "nästan|almost|adv.|Jag är nästan klar.",
  "knappast|hardly|adv.|Det händer knappast.",
  "ganska|quite|adv.|Ganska kallt idag.",
  "väldigt|very|adv.|Väldigt gott!",
  "ungefär|approximately|adv.|Ungefär tio minuter.",
  "minst|at least|adv.|Minst en timme.",
  "mest|most|adv.|Det jag gillar mest.",
  "särskilt|especially|adv.|Särskilt på vintern.",
  "framför allt|above all|phrase|Framför allt behöver vi vila.",
  "å andra sidan|on the other hand|phrase|Å andra sidan är det dyrt.",
  "med andra ord|in other words|phrase|Med andra ord, nej.",
  "för det mesta|mostly|phrase|För det mesta jobbar jag hemma.",
  "så småningom|eventually|phrase|Så småningom lär man sig.",
  "med tiden|over time|phrase|Med tiden blir det lättare.",
  "på egen hand|on one's own|phrase|Hon klarade det på egen hand.",
  "i stort sett|by and large|phrase|I stort sett är allt klart.",
  "när det gäller|when it comes to|phrase|När det gäller mat är han kräsen.",
  "å ena sidan|on one hand|phrase|Å ena sidan är det praktiskt.",
  "tvärtom|on the contrary|adv.|Tvärtom, jag gillar det.",
  "hur som helst|anyway|phrase|Hur som helst, vi ses.",
  "för tillfället|at the moment|phrase|För tillfället är jag ledig.",
  "på sikt|in the long run|phrase|På sikt sparar vi pengar.",
  "i alla fall|in any case|phrase|I alla fall tack för hjälpen.",
  "det beror på|it depends|phrase|Det beror på vädret.",
  "det gör inget|it doesn't matter|phrase|Det gör inget, ingen fara.",
  "ingen fara|no worries|phrase|Ingen fara, jag fixar det.",
  "vad menar du?|what do you mean?|phrase|Vad menar du med det?",
  "kan du upprepa?|can you repeat?|phrase|Kan du upprepa, tack?",
  "jag håller med|I agree|phrase|Jag håller med dig.",
  "jag håller inte med|I disagree|phrase|Jag håller inte med alls.",
  "jag är inte säker|I'm not sure|phrase|Jag är inte säker på det.",
  "vi hörs|talk soon|phrase|Vi hörs på fredag!",
  "vi ses|see you|phrase|Vi ses imorgon.",
  "lycka till|good luck|phrase|Lycka till på provet!",
  "ha det bra|take care|phrase|Ha det bra i helgen!",
  "kul att höra|glad to hear|phrase|Kul att höra att det gick bra.",
  "tyvärr|unfortunately|adv.|Tyvärr kan jag inte komma.",
  "gärna|gladly|adv.|Jag kommer gärna.",
  "helst|preferably|adv.|Helst på morgonen.",
  "definitivt|definitely|adv.|Det är definitivt bättre.",
  "möjligen|possibly|adv.|Möjligen imorgon.",
  "antagligen|probably|adv.|Han kommer antagligen sent.",
  "säkerligen|surely|adv.|Det är säkerligen sant.",
  "noggrann|careful, thorough|adj.|Hon är mycket noggrann.",
  "pålitlig|reliable|adj.|En pålitlig kollega.",
  "envis|stubborn|adj.|Han är envis.",
  "lugn|calm|adj.|Håll dig lugn.",
  "stressad|stressed|adj.|Jag är stressad idag.",
  "besviken|disappointed|adj.|Jag blev besviken.",
  "nöjd|satisfied|adj.|Jag är nöjd med resultatet.",
  "orolig|worried|adj.|Hon är orolig för provet.",
  "medveten|aware|adj.|Jag är medveten om risken.",
  "nyfiken|curious|adj.|Jag är nyfiken på boken.",
  "försiktig|cautious|adj.|Var försiktig på isen.",
  "tydlig|clear|adj.|Ett tydligt svar.",
  "otydlig|unclear|adj.|Instruktionen var otydlig.",
  "viktig|important|adj.|En viktig fråga.",
  "onödig|unnecessary|adj.|En onödig kostnad.",
  "vanlig|common|adj.|Ett vanligt problem.",
  "ovanlig|unusual|adj.|Ett ovanligt namn.",
  "möjlig|possible|adj.|Är det möjligt?",
  "omöjlig|impossible|adj.|Det är omöjligt idag.",
  "tillräcklig|sufficient|adj.|Tillräckligt med tid.",
  "ledig|free, available|adj.|Är stolen ledig?",
  "upptagen|busy|adj.|Jag är upptagen nu.",
  "trångt|cramped|adj.|Det är trångt på bussen.",
  "praktisk|practical|adj.|En praktisk lösning.",
  "rimlig|reasonable|adj.|Ett rimligt pris.",
  "orättvis|unfair|adj.|Det känns orättvist.",
  "sällan|rarely|adv.|Jag går sällan ut.",
  "genast|immediately|adv.|Kom genast!",
  "strax|shortly|adv.|Jag kommer strax.",
  "nyligen|recently|adv.|Vi flyttade nyligen.",
  "förut|before, previously|adv.|Vi har träffats förut.",
  "framöver|going forward|adv.|Framöver blir det bättre.",
  "samtidigt|at the same time|adv.|Vi kom samtidigt.",
  "plötsligt|suddenly|adv.|Plötsligt slocknade ljuset.",
  "äntligen|finally|adv.|Äntligen helg!",
  "numera|nowadays|adv.|Numera jobbar jag hemma.",
  "att bry sig om|to care about|v.|Han bryr sig om detaljer.",
  "att komma överens|to get along, agree|v.|Vi kom överens om priset.",
  "att ta hand om|to take care of|v.|Hon tar hand om barnen.",
  "att se fram emot|to look forward to|v.|Jag ser fram emot resan.",
  "att ge upp|to give up|v.|Ge inte upp nu.",
  "att ta reda på|to find out|v.|Jag tar reda på tiden.",
  "att stå ut med|to put up with|v.|Jag står inte ut med bullret.",
  "att hålla med|to agree|v.|Jag håller med dig.",
  "att räkna med|to count on|v.|Räkna med regn.",
  "att titta förbi|to drop by|v.|Titta förbi ikväll!",
];

export const intermediateCards = rowsToCards("i", rows);
