import { rowsToCards } from "./flashcard-types";

const rows = [
  "hej|hello|interj.|Hej! Hur mår du?",
  "hejsan|hi there|interj.|Hejsan, vad gör du?",
  "hej då|goodbye|phrase|Hej då, vi ses imorgon!",
  "god morgon|good morning|phrase|God morgon! Sovit gott?",
  "god kväll|good evening|phrase|God kväll, välkommen in.",
  "god natt|good night|phrase|God natt, sov gott.",
  "tack|thank you|interj.|Tack så mycket.",
  "tack så mycket|thank you very much|phrase|Tack så mycket för hjälpen.",
  "varsågod|you're welcome / here you go|interj.|Varsågod, sitt ner.",
  "ursäkta|excuse me, sorry|interj.|Ursäkta, var är stationen?",
  "förlåt|sorry|interj.|Förlåt, jag är sen.",
  "ja|yes|adv.|Ja, det förstår jag.",
  "nej|no|adv.|Nej, tack.",
  "kanske|maybe|adv.|Kanske imorgon.",
  "snälla|please|adv.|Hjälp mig, snälla.",
  "hur mår du?|how are you?|phrase|Hej Anna, hur mår du?",
  "jag mår bra|I'm fine|phrase|Jag mår bra, tack.",
  "vad heter du?|what's your name?|phrase|Hej, vad heter du?",
  "jag heter|my name is|phrase|Jag heter Erik.",
  "trevligt att träffas|nice to meet you|phrase|Trevligt att träffas!",
  "jag förstår inte|I don't understand|phrase|Ursäkta, jag förstår inte.",
  "kan du prata långsammare?|can you speak slower?|phrase|Kan du prata långsammare, tack?",
  "talar du engelska?|do you speak English?|phrase|Ursäkta, talar du engelska?",
  "jag vet inte|I don't know|phrase|Jag vet inte var det är.",
  "vad kostar det?|how much is it?|phrase|Vad kostar det, tack?",
  "var är toaletten?|where is the toilet?|phrase|Ursäkta, var är toaletten?",
  "jag|I|pron.|Jag bor i Sverige.",
  "du|you|pron.|Du är snäll.",
  "han|he|pron.|Han arbetar idag.",
  "hon|she|pron.|Hon läser en bok.",
  "vi|we|pron.|Vi går hem nu.",
  "de|they|pron.|De bor i Malmö.",
  "min|my|pron.|Min syster heter Lena.",
  "din|your|pron.|Är det din bil?",
  "vem|who|pron.|Vem är det?",
  "vad|what|pron.|Vad gör du?",
  "var|where|adv.|Var bor du?",
  "när|when|adv.|När kommer tåget?",
  "hur|how|adv.|Hur gör man det?",
  "varför|why|adv.|Varför är du ledsen?",
  "vilken|which|pron.|Vilken buss går till stan?",
  "här|here|adv.|Jag väntar här.",
  "där|there|adv.|Boken ligger där.",
  "nu|now|adv.|Vi börjar nu.",
  "sedan|then, later|adv.|Vi äter sedan.",
  "idag|today|adv.|Idag är det soligt.",
  "imorgon|tomorrow|adv.|Vi ses imorgon.",
  "igår|yesterday|adv.|Igår regnade det.",
  "alltid|always|adv.|Jag dricker alltid kaffe.",
  "aldrig|never|adv.|Jag äter aldrig kött.",
  "ofta|often|adv.|Vi ses ofta.",
  "ibland|sometimes|adv.|Ibland tar jag bussen.",
  "vatten|water|n.|Ett glas vatten, tack.",
  "kaffe|coffee|n.|Jag vill ha kaffe.",
  "te|tea|n.|Te med mjölk, tack.",
  "mjölk|milk|n.|Mjölken står i kylen.",
  "bröd|bread|n.|Brödet är färskt.",
  "smör|butter|n.|Smör på brödet.",
  "ost|cheese|n.|Jag gillar svensk ost.",
  "ägg|egg|n.|Två ägg till frukost.",
  "kött|meat|n.|Vi äter inte kött.",
  "fisk|fish|n.|Fisken är god.",
  "potatis|potato|n.|Kokt potatis till middag.",
  "sallad|salad|n.|En grön sallad.",
  "frukt|fruit|n.|Frukt är nyttigt.",
  "äpple|apple|n.|Ett rött äpple.",
  "banan|banana|n.|Jag äter en banan.",
  "socker|sugar|n.|Kaffe utan socker.",
  "salt|salt|n.|Kan du skicka saltet?",
  "middag|dinner|n.|Middagen är klar.",
  "frukost|breakfast|n.|Frukost klockan sju.",
  "lunch|lunch|n.|Vi äter lunch nu.",
  "mat|food|n.|Maten är god.",
  "restaurang|restaurant|n.|En trevlig restaurang.",
  "kafé|café|n.|Vi träffas på ett kafé.",
  "hus|house|n.|Ett litet hus i skogen.",
  "hem|home|n.|Jag går hem.",
  "lägenhet|apartment|n.|Vi bor i en lägenhet.",
  "rum|room|n.|Rummet är stort.",
  "kök|kitchen|n.|Köket är nytt.",
  "bord|table|n.|Vi sitter vid bordet.",
  "stol|chair|n.|Stolen är bekväm.",
  "soffa|sofa|n.|Katten sover på soffan.",
  "säng|bed|n.|Sängen är mjuk.",
  "dörr|door|n.|Stäng dörren.",
  "fönster|window|n.|Öppna fönstret, tack.",
  "nyckel|key|n.|Var är min nyckel?",
  "lampa|lamp|n.|Tänd lampan.",
  "bok|book|n.|Boken ligger på bordet.",
  "telefon|phone|n.|Min telefon är död.",
  "dator|computer|n.|Datorn är långsam.",
  "pengar|money|n.|Jag har inga pengar.",
  "väska|bag|n.|Väskan är tung.",
  "kläder|clothes|n.|Kläderna är rena.",
  "jacka|jacket|n.|Ta med en jacka.",
  "skor|shoes|n.|Nya skor är dyra.",
  "tröja|sweater|n.|En varm tröja.",
  "byxor|trousers|n.|Byxorna är blå.",
  "familj|family|n.|Hela familjen är här.",
  "mamma|mum|n.|Min mamma bakar bröd.",
  "pappa|dad|n.|Pappa kör bilen.",
  "syster|sister|n.|Jag har en syster.",
  "bror|brother|n.|Min bror är lärare.",
  "barn|child|n.|Barnet sover.",
  "vän|friend|n.|Hon är min bästa vän.",
  "man|man|n.|En man väntar där.",
  "kvinna|woman|n.|Kvinnan läser tidningen.",
  "flicka|girl|n.|Flickan sjunger.",
  "pojke|boy|n.|Pojken spelar fotboll.",
  "hund|dog|n.|Hunden springer i parken.",
  "katt|cat|n.|Katten sover på soffan.",
  "häst|horse|n.|Hästen är stor.",
  "fågel|bird|n.|En fågel sitter i trädet.",
  "träd|tree|n.|Trädet är gammalt.",
  "blomma|flower|n.|En vacker blomma.",
  "skog|forest|n.|Vi går i skogen.",
  "sjö|lake|n.|Sjön är kall.",
  "hav|sea|n.|Havet är blått.",
  "sol|sun|n.|Solen skiner.",
  "regn|rain|n.|Regnet slutade.",
  "snö|snow|n.|Snön faller mjukt.",
  "vind|wind|n.|Vinden är stark.",
  "himmel|sky|n.|Himlen är klar.",
  "väder|weather|n.|Vilket vackert väder!",
  "sommar|summer|n.|Sommaren är kort.",
  "vinter|winter|n.|Vintern är lång.",
  "höst|autumn|n.|Hösten är vacker.",
  "vår|spring|n.|Våren kommer sent.",
  "dag|day|n.|Vilken fin dag.",
  "natt|night|n.|Natten är tyst.",
  "vecka|week|n.|Nästa vecka reser vi.",
  "månad|month|n.|Om en månad.",
  "år|year|n.|Ett år går fort.",
  "timme|hour|n.|Om en timme.",
  "minut|minute|n.|Vänta en minut.",
  "klocka|clock, watch|n.|Klockan är tre.",
  "måndag|Monday|n.|Vi ses på måndag.",
  "tisdag|Tuesday|n.|Tisdag passar bra.",
  "onsdag|Wednesday|n.|Onsdag är travel.",
  "torsdag|Thursday|n.|Torsdag kväll.",
  "fredag|Friday|n.|Äntligen fredag!",
  "lördag|Saturday|n.|Lördag sover jag länge.",
  "söndag|Sunday|n.|Söndag är vilodag.",
  "en|one|num.|En kopp kaffe.",
  "två|two|num.|Två biljetter, tack.",
  "tre|three|num.|Tre barn.",
  "fyra|four|num.|Fyra stolar.",
  "fem|five|num.|Fem minuter kvar.",
  "sex|six|num.|Klockan sex.",
  "sju|seven|num.|Sju dagar.",
  "åtta|eight|num.|Åtta personer.",
  "nio|nine|num.|Tåget går klockan nio.",
  "tio|ten|num.|Tio kronor.",
  "hundra|hundred|num.|Hundra kronor.",
  "tusen|thousand|num.|Tusen tack!",
  "röd|red|adj.|Bilen är röd.",
  "blå|blue|adj.|En blå himmel.",
  "grön|green|adj.|Gröna blad.",
  "gul|yellow|adj.|Ett gult hus.",
  "vit|white|adj.|Vit snö.",
  "svart|black|adj.|En svart katt.",
  "stor|big|adj.|Ett stort rum.",
  "liten|small|adj.|En liten hund.",
  "bra|good|adj.|Det är bra.",
  "dålig|bad|adj.|Dåligt väder idag.",
  "ny|new|adj.|En ny bok.",
  "gammal|old|adj.|Ett gammalt hus.",
  "varm|warm|adj.|Varmt vatten.",
  "kall|cold|adj.|Kallt ute.",
  "snabb|fast|adj.|Ett snabbt tåg.",
  "långsam|slow|adj.|Långsam trafik.",
  "dyr|expensive|adj.|Det är för dyrt.",
  "billig|cheap|adj.|En billig biljett.",
  "lätt|easy, light|adj.|Svenska är inte lätt.",
  "svår|difficult|adj.|En svår fråga.",
  "trött|tired|adj.|Jag är trött.",
  "glad|happy|adj.|Hon är glad idag.",
  "ledsen|sad|adj.|Han är ledsen.",
  "hungrig|hungry|adj.|Jag är hungrig.",
  "törstig|thirsty|adj.|Är du törstig?",
  "vacker|beautiful|adj.|En vacker sång.",
  "att vara|to be|v.|Jag är hemma.",
  "att ha|to have|v.|Jag har en fråga.",
  "att göra|to do, to make|v.|Vad gör du?",
  "att gå|to walk, to go|v.|Vi går till parken.",
  "att komma|to come|v.|Kommer du ikväll?",
  "att äta|to eat|v.|Vi äter klockan sex.",
  "att dricka|to drink|v.|Jag dricker te.",
  "att sova|to sleep|v.|Barnen sover redan.",
  "att bo|to live, to reside|v.|Jag bor i Uppsala.",
  "att tala|to speak|v.|Han talar svenska.",
  "att säga|to say|v.|Vad sa du?",
  "att se|to see|v.|Jag ser dig.",
  "att höra|to hear|v.|Hör du musiken?",
  "att läsa|to read|v.|Jag läser en bok.",
  "att skriva|to write|v.|Skriv ditt namn.",
  "att köpa|to buy|v.|Jag ska köpa bröd.",
  "att arbeta|to work|v.|Hon arbetar hemma.",
  "att lära|to learn, to teach|v.|Jag lär mig svenska.",
  "att förstå|to understand|v.|Nu förstår jag.",
  "att tycka om|to like|v.|Jag tycker om kaffe.",
  "att vilja|to want|v.|Jag vill sova.",
  "att kunna|to be able to|v.|Kan du hjälpa mig?",
  "att behöva|to need|v.|Jag behöver vila.",
  "att hjälpa|to help|v.|Kan du hjälpa mig?",
  "att vänta|to wait|v.|Vänta på mig!",
  "att öppna|to open|v.|Öppna dörren.",
  "att stänga|to close|v.|Stäng fönstret.",
  "gata|street|n.|Gatan är tom.",
  "stad|city|n.|En vacker stad.",
  "land|country|n.|Sverige är ett kallt land.",
  "buss|bus|n.|Bussen är sen.",
  "tåg|train|n.|Tåget går klockan nio.",
  "bil|car|n.|Bilen är röd.",
  "cykel|bicycle|n.|Jag cyklar till jobbet.",
  "flygplan|airplane|n.|Flygplanet landar nu.",
  "biljett|ticket|n.|En biljett till Göteborg.",
  "skola|school|n.|Skolan börjar tidigt.",
  "jobb|job|n.|Jag har ett nytt jobb.",
  "affär|shop|n.|Affären stänger sex.",
  "sjukhus|hospital|n.|Sjukhuset ligger nära.",
  "apotek|pharmacy|n.|Finns ett apotek här?",
  "bank|bank|n.|Banken är stängd.",
  "hotell|hotel|n.|Ett litet hotell.",
];

export const beginnerCards = rowsToCards("b", rows);
