import { rowsToCards } from "./flashcard-types";

const rows = [
  "att ana|to sense, to suspect|v.|Jag anade oråd.",
  "att anta|to assume|v.|Vi antar att hon kommer.",
  "att antyda|to imply, to hint|v.|Han antydde en förändring.",
  "att avgöra|to determine|v.|Domaren avgjorde matchen.",
  "att avstå|to refrain, to decline|v.|Hon avstod från kommentar.",
  "att avvakta|to await|v.|Vi avvaktar beslutet.",
  "att bekräfta|to confirm|v.|Kan du bekräfta tiden?",
  "att bemöta|to respond to, to treat|v.|Han bemötte kritiken sakligt.",
  "att beröra|to touch, to affect|v.|Frågan berör oss alla.",
  "att betrakta|to regard, to consider|v.|Det betraktas som normalt.",
  "att bidra|to contribute|v.|Alla bidrog med idéer.",
  "att drabba|to strike, to affect|v.|Krisen drabbade många.",
  "att dröja|to be delayed, to linger|v.|Det dröjer en stund.",
  "att erkänna|to admit|v.|Han erkände sitt fel.",
  "att fastställa|to establish|v.|Orsaken är fastställd.",
  "att förbise|to overlook|v.|Vi förbisåg en detalj.",
  "att fördjupa|to deepen|v.|Kursen fördjupar kunskapen.",
  "att förebygga|to prevent|v.|Vi vill förebygga skador.",
  "att föredra|to prefer|v.|Jag föredrar tåg.",
  "att förhindra|to prevent|v.|Regnet förhindrade matchen.",
  "att förutsätta|to presuppose|v.|Det förutsätter tillstånd.",
  "att genomföra|to carry out|v.|Planen genomfördes i tid.",
  "att hantera|to handle|v.|Hon hanterade situationen väl.",
  "att inse|to realise|v.|Jag insåg mitt misstag.",
  "att innebära|to entail, to mean|v.|Det innebär mer arbete.",
  "att invända|to object|v.|Ingen invände mot förslaget.",
  "att medge|to concede|v.|Jag måste medge att du har rätt.",
  "att motsätta sig|to oppose|v.|De motsatte sig ändringen.",
  "att omfatta|to comprise|v.|Avtalet omfattar tre år.",
  "att påpeka|to point out|v.|Hon påpekade ett fel.",
  "att påstå|to claim|v.|Han påstår att han var där.",
  "att präglas av|to be characterised by|v.|Dagen präglades av oro.",
  "att rådfråga|to consult|v.|Rådfråga en jurist.",
  "att samordna|to coordinate|v.|Vi samordnar insatserna.",
  "att skildra|to depict|v.|Boken skildrar 1800-talet.",
  "att skärpa|to tighten, to sharpen|v.|Reglerna skärptes i år.",
  "att stärka|to strengthen|v.|Det stärker vår position.",
  "att sträva efter|to strive for|v.|Vi strävar efter balans.",
  "att särskilja|to distinguish|v.|Svårt att särskilja dem.",
  "att tillämpa|to apply|v.|Regeln tillämpas strikt.",
  "att tveka|to hesitate|v.|Tveka inte att ringa.",
  "att uppfatta|to perceive|v.|Jag uppfattade det annorlunda.",
  "att uppmuntra|to encourage|v.|Läraren uppmuntrade oss.",
  "att uppnå|to achieve|v.|Vi uppnådde målet.",
  "att upprätthålla|to maintain|v.|Vi upprätthåller ordningen.",
  "att utgå från|to assume, to start from|v.|Jag utgick från din text.",
  "att utmana|to challenge|v.|Han utmanade beslutet.",
  "att utnyttja|to utilise, to exploit|v.|Utnyttja tiden väl.",
  "att utveckla|to develop|v.|Vi utvecklar nya idéer.",
  "att åstadkomma|to accomplish|v.|Hon åstadkom mycket.",
  "att återspegla|to reflect|v.|Siffrorna återspeglar trenden.",
  "att övertyga|to convince|v.|Argumenten övertygade mig.",
  "att överväga|to consider|v.|Vi överväger ett byte.",
  "att ifrågasätta|to question|v.|Ingen ifrågasatte metoden.",
  "att gynna|to favour, to benefit|v.|Reformen gynnar små företag.",
  "att missgynna|to disadvantage|v.|Systemet missgynnar unga.",
  "att förvalta|to manage, to administer|v.|De förvaltar fonden.",
  "att avsätta|to set aside, to depose|v.|Vi avsatte tid för det.",
  "att tillhandahålla|to provide|v.|Vi tillhandahåller material.",
  "att verkställa|to execute, to enforce|v.|Beslutet verkställs i maj.",
  "förutsättning|prerequisite|n.|En viktig förutsättning.",
  "hänsyn|consideration|n.|Ta hänsyn till andra.",
  "innebörd|meaning, implication|n.|Ordets innebörd är oklar.",
  "omfattning|extent, scope|n.|Skadornas omfattning är stor.",
  "utveckling|development|n.|En positiv utveckling.",
  "sammanhang|context|n.|Ur sitt sammanhang.",
  "perspektiv|perspective|n.|Ett nytt perspektiv.",
  "avvägning|trade-off|n.|En svår avvägning.",
  "bedömning|assessment|n.|Min bedömning är annan.",
  "bemötande|treatment, response|n.|Ett gott bemötande.",
  "brist|shortage, flaw|n.|Brist på tid.",
  "överskott|surplus|n.|Ett litet överskott.",
  "underskott|deficit|n.|Ett växande underskott.",
  "tillväxt|growth|n.|Svag tillväxt i år.",
  "efterfrågan|demand|n.|Hög efterfrågan på bostäder.",
  "utbud|supply, range|n.|Ett brett utbud.",
  "villkor|condition, terms|n.|Rimliga villkor.",
  "åtgärd|measure, action|n.|En tillfällig åtgärd.",
  "insats|effort, contribution|n.|En stor insats.",
  "genomslag|impact|n.|Idén fick genomslag.",
  "utfall|outcome|n.|Ett oväntat utfall.",
  "avkastning|return, yield|n.|Låg avkastning i år.",
  "belastning|burden, load|n.|En tung belastning.",
  "bristande|lacking|adj.|Bristande underhåll.",
  "föredöme|role model|n.|Hon är ett föredöme.",
  "företräde|priority, precedence|n.|Barn har företräde.",
  "förbehåll|reservation|n.|Med visst förbehåll.",
  "hållbarhet|sustainability|n.|Hållbarhet är centralt.",
  "invändning|objection|n.|En rimlig invändning.",
  "jämlikhet|equality|n.|Jämlikhet i praktiken.",
  "medborgare|citizen|n.|Alla medborgare berörs.",
  "rättvisa|justice|n.|Kampen för rättvisa.",
  "samverkan|collaboration|n.|Samverkan mellan kommuner.",
  "trovärdighet|credibility|n.|Hans trovärdighet skadades.",
  "tillförlitlighet|reliability|n.|Datans tillförlitlighet.",
  "uppföljning|follow-up|n.|Uppföljning sker i höst.",
  "utgångspunkt|starting point|n.|Vår utgångspunkt är enkel.",
  "vederbörande|the person concerned|n.|Vederbörande har informerats.",
  "yttrande|statement, opinion|n.|Ett skriftligt yttrande.",
  "återhämtning|recovery|n.|En långsam återhämtning.",
  "överenskommelse|agreement|n.|En muntlig överenskommelse.",
  "avsikt|intention|n.|Det var inte min avsikt.",
  "beträffande|regarding|prep.|Beträffande din fråga...",
  "gällande|regarding, current|adj.|Gällande regler.",
  "enligt|according to|prep.|Enligt rapporten ökar antalet.",
  "utöver|in addition to|prep.|Utöver det behövs mer.",
  "inom|within|prep.|Inom en vecka.",
  "därmed|thereby|adv.|Därmed är saken avgjord.",
  "därav|of which, hence|adv.|Tio personer, därav tre barn.",
  "således|thus|adv.|Således är slutsatsen klar.",
  "följaktligen|consequently|adv.|Följaktligen avbröts mötet.",
  "emellertid|however|adv.|Emellertid finns ett problem.",
  "huruvida|whether|conj.|Oklart huruvida det stämmer.",
  "ifall|in case, if|conj.|Ifall det regnar stannar vi.",
  "såvida inte|unless|conj.|Såvida inte något ändras.",
  "förutsatt att|provided that|conj.|Förutsatt att alla kommer.",
  "i syfte att|in order to|phrase|I syfte att minska kostnader.",
  "med hänsyn till|in view of|phrase|Med hänsyn till vädret.",
  "till följd av|as a result of|phrase|Till följd av strejken.",
  "på grund av|because of|phrase|På grund av regnet.",
  "i och för sig|admittedly|phrase|I och för sig har du rätt.",
  "för den delen|for that matter|phrase|Inte jag heller, för den delen.",
  "i takt med|in step with|phrase|I takt med utvecklingen.",
  "med avseende på|with regard to|phrase|Med avseende på kostnaden.",
  "inte desto mindre|nonetheless|phrase|Inte desto mindre fortsatte de.",
  "vid närmare eftertanke|on second thought|phrase|Vid närmare eftertanke stannar jag.",
  "i värsta fall|worst case|phrase|I värsta fall får vi vänta.",
  "i bästa fall|at best|phrase|I bästa fall tar det en vecka.",
  "på det stora hela|all in all|phrase|På det stora hela gick det bra.",
  "utan vidare|without further ado|phrase|Han gick utan vidare.",
  "i regel|as a rule|phrase|I regel öppnar de nio.",
  "till skillnad från|unlike|phrase|Till skillnad från igår är det varmt.",
  "i jämförelse med|compared to|phrase|I jämförelse med förra året.",
  "under förutsättning att|on condition that|phrase|Under förutsättning att du kommer.",
  "att slå två fåglar i en smäll|to kill two birds with one stone|idiom|Vi slog två fåglar i en smäll.",
  "att ha tummen mitt i handen|to be all thumbs|idiom|Jag har tummen mitt i handen idag.",
  "att gå som på räls|to go smoothly|idiom|Presentationen gick som på räls.",
  "att kasta in handduken|to throw in the towel|idiom|Han kastade in handduken.",
  "att lägga näsan i blöt|to meddle|idiom|Lägg inte näsan i blöt.",
  "att ta det med en klackspark|to take it lightly|idiom|Hon tog det med en klackspark.",
  "att gilla läget|to accept the situation|idiom|Vi får gilla läget.",
  "att ana ugglor i mossen|to smell a rat|idiom|Jag anar ugglor i mossen.",
  "att gå på tomgång|to idle, spin one's wheels|idiom|Projektet går på tomgång.",
  "att sitta i sjön|to be in trouble|idiom|Nu sitter vi i sjön.",
  "att inte vara hela taket|to be a bit crazy|idiom|Han är inte hela taket.",
  "att göra en höna av en fjäder|to make a mountain of a molehill|idiom|Gör inte en höna av en fjäder.",
  "att skjuta upp något|to postpone something|v.|Vi sköt upp mötet.",
  "att smida medan järnet är varmt|to strike while the iron is hot|idiom|Smid medan järnet är varmt.",
  "att sätta punkt|to put an end to|idiom|Vi satte punkt för debatten.",
  "att tala i egen sak|to have a vested interest|idiom|Han talar i egen sak.",
  "att vara på tapeten|to be on the agenda|idiom|Frågan är på tapeten igen.",
  "att ha is i magen|to keep one's cool|idiom|Ha is i magen nu.",
  "att bita i det sura äpplet|to bite the bullet|idiom|Vi får bita i det sura äpplet.",
  "att kasta ljus över|to shed light on|idiom|Rapporten kastar ljus över frågan.",
  "avgörande|decisive, crucial|adj.|Ett avgörande ögonblick.",
  "betydande|significant|adj.|En betydande ökning.",
  "genomgripande|far-reaching|adj.|En genomgripande reform.",
  "påtaglig|noticeable, tangible|adj.|En påtaglig förbättring.",
  "omfattande|extensive|adj.|Ett omfattande arbete.",
  "väsentlig|essential|adj.|En väsentlig skillnad.",
  "oundviklig|inevitable|adj.|En oundviklig följd.",
  "godtycklig|arbitrary|adj.|Ett godtyckligt urval.",
  "tvetydig|ambiguous|adj.|Ett tvetydigt svar.",
  "entydig|unambiguous|adj.|Ett entydigt resultat.",
  "långsiktig|long-term|adj.|En långsiktig plan.",
  "kortsiktig|short-term|adj.|En kortsiktig lösning.",
  "ihållande|persistent|adj.|Ihållande regn.",
  "återkommande|recurring|adj.|Ett återkommande problem.",
  "utbredd|widespread|adj.|En utbredd uppfattning.",
  "sparsam|frugal|adj.|Han är sparsam med ord.",
  "träffsäker|accurate, apt|adj.|En träffsäker analys.",
  "vederhäftig|trustworthy, sound|adj.|En vederhäftig källa.",
  "påfrestande|demanding, stressful|adj.|En påfrestande period.",
  "gedigen|solid, thorough|adj.|En gedigen utbildning.",
  "framstående|prominent|adj.|En framstående forskare.",
  "ansedd|respected|adj.|En ansedd tidning.",
  "lovvärd|commendable|adj.|Ett lovvärt initiativ.",
  "föredömlig|exemplary|adj.|Ett föredömligt arbete.",
  "besvärlig|troublesome|adj.|En besvärlig situation.",
  "knapphändig|scant|adj.|Knapphändig information.",
  "överhängande|imminent|adj.|En överhängande risk.",
  "framgångsrik|successful|adj.|En framgångsrik satsning.",
  "eftertraktad|sought-after|adj.|En eftertraktad tjänst.",
  "otvivelaktigt|undoubtedly|adv.|Otvivelaktigt det bästa valet.",
  "onekligen|undeniably|adv.|Onekligen imponerande.",
  "företrädesvis|preferably, mainly|adv.|Företrädesvis på morgonen.",
  "huvudsakligen|mainly|adv.|Huvudsakligen unga deltog.",
  "delvis|partly|adv.|Delvis rätt.",
  "uteslutande|exclusively|adv.|Uteslutande för medlemmar.",
  "tillika|as well as|adv.|Chef tillika ägare.",
  "förvisso|certainly, admittedly|adv.|Förvisso sant, men dyrt.",
  "sannolikt|likely|adv.|Sannolikt blir det regn.",
  "eventuellt|possibly|adv.|Eventuellt flyttar vi mötet.",
  "företag|company|n.|Ett litet företag i Malmö.",
  "styrelse|board|n.|Styrelsen sammanträder i maj.",
  "budget|budget|n.|Budgeten är stram.",
  "kostnad|cost|n.|Kostnaden är hög.",
  "intäkt|revenue|n.|Intäkterna ökade.",
  "investering|investment|n.|En långsiktig investering.",
  "marknad|market|n.|En växande marknad.",
  "konkurrens|competition|n.|Hård konkurrens i branschen.",
  "bransch|industry|n.|Branschen förändras snabbt.",
  "kundkrets|customer base|n.|En lojal kundkrets.",
  "leverantör|supplier|n.|Vår viktigaste leverantör.",
  "upphandling|procurement|n.|En offentlig upphandling.",
  "redovisning|accounting, reporting|n.|Redovisningen är klar.",
  "revision|audit|n.|Revisionen visade brister.",
  "tillsyn|supervision|n.|Tillsynen skärps.",
  "bostadsbrist|housing shortage|n.|Bostadsbristen ökar.",
  "arbetslöshet|unemployment|n.|Arbetslösheten sjönk.",
  "inflation|inflation|n.|Inflationen dämpas.",
  "utsläpp|emissions|n.|Utsläppen måste minska.",
  "klimatförändring|climate change|n.|Klimatförändringen märks.",
  "forskning|research|n.|Ny forskning visar detta.",
  "undersökning|survey, study|n.|En stor undersökning.",
  "slutsats|conclusion|n.|Slutsatsen är tydlig.",
  "källa|source|n.|En pålitlig källa.",
  "bevis|evidence|n.|Det finns starka bevis.",
  "påstående|claim, statement|n.|Ett djärvt påstående.",
  "resonemang|line of reasoning|n.|Ett tydligt resonemang.",
  "invänding mot|objection to|n.|En invänding mot metoden.",
  "motargument|counterargument|n.|Ett starkt motargument.",
  "nyansering|nuance|n.|Frågan kräver nyansering.",
  "tolkning|interpretation|n.|En annan tolkning.",
  "förhandling|negotiation|n.|Förhandlingarna pågår.",
  "kompromiss|compromise|n.|Vi nådde en kompromiss.",
  "eftergift|concession|n.|En liten eftergift.",
  "beslutsfattare|decision maker|n.|Beslutsfattarna dröjer.",
  "handläggare|case officer|n.|Min handläggare ringde.",
  "ärende|case, matter|n.|Ditt ärende behandlas.",
  "överklagan|appeal|n.|Vi lämnade in en överklagan.",
  "domstol|court|n.|Målet gick till domstol.",
  "lagstiftning|legislation|n.|Ny lagstiftning från juli.",
  "föreskrift|regulation|n.|Enligt gällande föreskrifter.",
];

export const advancedCards = rowsToCards("a", rows);
