export type Flashcard = {
  id: string;
  swedish: string;
  english: string;
  pronunciation?: string;
  partOfSpeech?: string;
  example?: string;
};

export type Level = {
  id: string;
  name: string;
  description: string;
  duration: string;
  cards: Flashcard[];
};

const b = (
  id: string,
  swedish: string,
  english: string,
  pronunciation: string,
  partOfSpeech: string,
  example: string
): Flashcard => ({ id, swedish, english, pronunciation, partOfSpeech, example });

export const levels: Level[] = [
  {
    id: "beginner",
    name: "Beginner",
    description: "Essential greetings & first words",
    duration: "10 min",
    cards: [
      b("b1", "hej", "hello", "/hej/", "interj.", "Hej! Hur mår du?"),
      b("b2", "tack", "thank you", "/tak/", "interj.", "Tack så mycket."),
      b("b3", "ja", "yes", "/jaː/", "adv.", "Ja, det förstår jag."),
      b("b4", "nej", "no", "/nɛj/", "adv.", "Nej, tack."),
      b("b5", "vatten", "water", "/ˈvatːɛn/", "n.", "Ett glas vatten, tack."),
      b("b6", "kaffe", "coffee", "/ˈkafːɛ/", "n.", "Jag vill ha kaffe."),
      b("b7", "bröd", "bread", "/brøːd/", "n.", "Brödet är färskt."),
      b("b8", "hus", "house", "/hʉːs/", "n.", "Ett litet hus i skogen."),
      b("b9", "hund", "dog", "/hɵnd/", "n.", "Hunden springer i parken."),
      b("b10", "katt", "cat", "/kat/", "n.", "Katten sover på soffan."),
      b("b11", "god morgon", "good morning", "/ɡuːd ˈmɔrːjɔn/", "phrase", "God morgon! Sovit gott?"),
      b("b12", "hej då", "goodbye", "/hej doː/", "phrase", "Hej då, vi ses imorgon!"),
      b("b13", "god kväll", "good evening", "/ɡuːd ˈkʋɛlː/", "phrase", "God kväll, välkommen in."),
      b("b14", "ursäkta", "excuse me, sorry", "/ɵˈɧɛkːta/", "interj.", "Ursäkta, var är stationen?"),
      b("b15", "varsågod", "you're welcome, here you go", "/vaɂˈɡoːd/", "interj.", "Varsågod, sitt ner."),
      b("b16", "snälla", "please", "/ˈɧnɛlːa/", "adv.", "Hjälp mig, snälla."),
      b("b17", "bok", "book", "/buːk/", "n.", "Boken ligger på bordet."),
      b("b18", "stol", "chair", "/stuːl/", "n.", "Stolen är bekväm."),
      b("b19", "bord", "table", "/buːɖ/", "n.", "Vi sitter vid bordet."),
      b("b20", "fönster", "window", "/ˈfœnːstɛr/", "n.", "Öppna fönstret, tack."),
      b("b21", "dörr", "door", "/dœrː/", "n.", "Stäng dörren."),
      b("b22", "bil", "car", "/biːl/", "n.", "Bilen är röd."),
      b("b23", "cykel", "bicycle", "/ˈsʏkːɛl/", "n.", "Jag cyklar till jobbet."),
      b("b24", "tåg", "train", "/toːɡ/", "n.", "Tåget går klockan nio."),
      b("b25", "skola", "school", "/ˈɧkoːla/", "n.", "Skolan börjar tidigt."),
      b("b26", "vän", "friend", "/vɛnː/", "n.", "Hon är min bästa vän."),
      b("b27", "familj", "family", "/faˈmɪlːj/", "n.", "Hela familjen är här."),
      b("b28", "mamma", "mum", "/ˈmamːa/", "n.", "Min mamma bor i Göteborg."),
      b("b29", "pappa", "dad", "/ˈpapːa/", "n.", "Pappa lagar mat ikväll."),
      b("b30", "barn", "child, children", "/bɑːɳ/", "n.", "Barnen leker utanför."),
      b("b31", "mat", "food", "/mɑːt/", "n.", "Maten är klar."),
      b("b32", "mjölk", "milk", "/mjœlk/", "n.", "Mjölken står i kylen."),
      b("b33", "äpple", "apple", "/ˈɛpːlɛ/", "n.", "Jag äter ett äpple."),
      b("b34", "ost", "cheese", "/uːst/", "n.", "Osten är god."),
      b("b35", "socker", "sugar", "/ˈsɔkːɛr/", "n.", "Tar du socker i kaffet?"),
      b("b36", "salt", "salt", "/salt/", "n.", "Kan du skicka saltet?"),
      b("b37", "en", "one", "/eːn/", "num.", "En kopp te, tack."),
      b("b38", "två", "two", "/tvoː/", "num.", "Två biljetter, tack."),
      b("b39", "tre", "three", "/treː/", "num.", "Vi är tre syskon."),
      b("b40", "fyra", "four", "/ˈfʉːra/", "num.", "Vi ses klockan fyra."),
      b("b41", "fem", "five", "/fɛm/", "num.", "Det kostar fem kronor."),
      b("b42", "idag", "today", "/ɪˈdaːɡ/", "adv.", "Vad gör du idag?"),
      b("b43", "imorgon", "tomorrow", "/ɪˈmɔrːjɔn/", "adv.", "Vi ses imorgon."),
      b("b44", "igår", "yesterday", "/ɪˈɡoːr/", "adv.", "Det regnade igår."),
      b("b45", "dag", "day", "/dɑːɡ/", "n.", "En fin dag."),
      b("b46", "natt", "night", "/natː/", "n.", "God natt, sov gott."),
      b("b47", "måne", "moon", "/ˈmoːnɛ/", "n.", "Månen är stor ikväll."),
      b("b48", "sol", "sun", "/suːl/", "n.", "Solen skiner idag."),
      b("b49", "regn", "rain", "/rɛɡːn/", "n.", "Det blir regn imorgon."),
      b("b50", "snö", "snow", "/snøː/", "n.", "Snön täcker gatorna."),
      b("b51", "vinter", "winter", "/ˈvɪnːtɛr/", "n.", "Vintern är lång i norr."),
      b("b52", "sommar", "summer", "/ˈsɔmːar/", "n.", "Jag älskar sommaren."),
      b("b53", "stor", "big", "/stuːr/", "adj.", "Huset är stort."),
      b("b54", "liten", "small", "/ˈliːtɛn/", "adj.", "En liten katt."),
      b("b55", "bra", "good", "/brɑː/", "adj.", "Det är bra, tack."),
      b("b56", "dålig", "bad", "/ˈdoːlɪɡ/", "adj.", "Jag mår dåligt idag."),
      b("b57", "varm", "warm", "/vamː/", "adj.", "Kaffet är varmt."),
      b("b58", "kall", "cold", "/kalː/", "adj.", "Vattnet är kallt."),
      b("b59", "ny", "new", "/nyː/", "adj.", "Min nya telefon."),
      b("b60", "gammal", "old", "/ˈɡamːal/", "adj.", "Ett gammalt hus."),
    ],
  },
  {
    id: "intermediate",
    name: "Intermediate",
    description: "Everyday phrases & small talk",
    duration: "12 min",
    cards: [
      b("i1", "stilla", "calm, still", "/ˈsɪlːa/", "adj.", "Havet är stilla ikväll."),
      b("i2", "en promenad", "a walk", "/ɛn prɔmɛˈnaːd/", "n. phrase", "En lång promenad i parken."),
      b("i3", "fika", "coffee break (with something sweet)", "/ˈfiːka/", "n.", "Ska vi ta en fika?"),
      b("i4", "lagom", "just right, not too much or too little", "/ˈlaːɡɔm/", "adj.", "Lagom är bäst."),
      b("i5", "mysig", "cozy", "/ˈmyːsɪɡ/", "adj.", "Vilken mysig lägenhet!"),
      b("i6", "förstå", "understand", "/fɛrˈstoː/", "v.", "Jag förstår inte."),
      b("i7", "kanske", "maybe", "/ˈkanːsɛ/", "adv.", "Kanske vi ses senare."),
      b("i8", "redan", "already", "/ˈreːdan/", "adv.", "Han är redan här."),
      b("i9", "vänta", "wait", "/ˈvɛnːta/", "v.", "Vänta ett ögonblick."),
      b("i10", "tycker om", "like, enjoy", "/ˈtʏkɛr ɔm/", "v. phrase", "Jag tycker om att läsa."),
      b("i11", "trött", "tired", "/trœt/", "adj.", "Jag är så trött idag."),
      b("i12", "glad", "happy", "/ɡlaːd/", "adj.", "Hon är alltid glad."),
      b("i13", "ledsen", "sad, sorry", "/ˈleːdsɛn/", "adj.", "Jag är ledsen att höra det."),
      b("i14", "hungrig", "hungry", "/ˈhɵŋːrɪɡ/", "adj.", "Är du hungrig?"),
      b("i15", "törstig", "thirsty", "/ˈtœʂːtɪɡ/", "adj.", "Jag är jättetörstig."),
      b("i16", "jobba", "work", "/ˈjɔbːa/", "v.", "Jag jobbar hemifrån."),
      b("i17", "sovа".replace("а","a"), "sleep", "/ˈsoːva/", "v.", "Jag måste sova nu."),
      b("i18", "vakna", "wake up", "/ˈvakːna/", "v.", "Jag vaknar tidigt."),
      b("i19", "laga mat", "cook", "/ˈlɑːɡa mɑːt/", "v. phrase", "Vi lagar mat tillsammans."),
      b("i20", "handla", "shop, buy groceries", "/ˈhanːdla/", "v.", "Jag ska handla efter jobbet."),
      b("i21", "städa", "clean", "/ˈstɛːda/", "v.", "Vi städar på lördagar."),
      b("i22", "tvätta", "wash", "/ˈtvɛtːa/", "v.", "Jag tvättar kläder idag."),
      b("i23", "ringa", "call (on the phone)", "/ˈrɪŋːa/", "v.", "Jag ringer dig senare."),
      b("i24", "skicka", "send", "/ˈɧɪkːa/", "v.", "Skicka mig ett meddelande."),
      b("i25", "träffa", "meet", "/ˈtrɛfːa/", "v.", "Ska vi träffas på fredag?"),
      b("i26", "bjuda in", "invite", "/ˈbjʉːd ɪn/", "v. phrase", "Vi bjuder in grannarna."),
      b("i27", "köpa", "buy", "/ˈɕøːpa/", "v.", "Jag köper en ny jacka."),
      b("i28", "sälja", "sell", "/ˈsɛlːja/", "v.", "De säljer sitt hus."),
      b("i29", "betala", "pay", "/bɛˈtɑːla/", "v.", "Kan jag betala med kort?"),
      b("i30", "kosta", "cost", "/ˈkɔsːta/", "v.", "Vad kostar den?"),
      b("i31", "billig", "cheap", "/ˈbɪlːiːɡ/", "adj.", "Den var billig."),
      b("i32", "dyr", "expensive", "/dyːr/", "adj.", "Det är för dyrt."),
      b("i33", "ledig", "free, off (work)", "/ˈleːdɪɡ/", "adj.", "Jag är ledig på måndag."),
      b("i34", "upptagen", "busy", "/ˈɵpːˌtɑːɡɛn/", "adj.", "Jag är upptagen just nu."),
      b("i35", "tidig", "early", "/ˈtiːdɪɡ/", "adj.", "Vi går upp tidigt."),
      b("i36", "sen", "late", "/seːn/", "adj.", "Förlåt att jag är sen."),
      b("i37", "snabb", "fast", "/snabː/", "adj.", "En snabb bil."),
      b("i38", "långsam", "slow", "/ˈloːŋˌsɑmː/", "adj.", "Tåget är långsamt idag."),
      b("i39", "lätt", "easy, light", "/lɛtː/", "adj.", "Det var lätt!"),
      b("i40", "svår", "difficult", "/svoːr/", "adj.", "Frågan är svår."),
      b("i41", "viktig", "important", "/ˈvɪkːtɪɡ/", "adj.", "Ett viktigt möte."),
      b("i42", "rolig", "fun, funny", "/ˈruːlɪɡ/", "adj.", "Filmen var rolig."),
      b("i43", "tråkig", "boring", "/ˈtroːkɪɡ/", "adj.", "Vilket tråkigt väder."),
      b("i44", "fin", "nice, beautiful", "/fiːn/", "adj.", "Vilken fin tröja!"),
      b("i45", "ful", "ugly", "/fʉːl/", "adj.", "En ful fågel? Nej, den är söt."),
      b("i46", "rent", "clean", "/reːn/", "adj.", "Köket är rent nu."),
      b("i47", "smutsig", "dirty", "/ˈsmɵtːsɪɡ/", "adj.", "Skorna är smutsiga."),
      b("i48", "säker", "safe, sure", "/ˈsɛːkɛr/", "adj.", "Är du säker?"),
      b("i49", "möjlig", "possible", "/ˈmøːjlɪɡ/", "adj.", "Allt är möjligt."),
      b("i50", "omöjlig", "impossible", "/ˈɔmːøːjlɪɡ/", "adj.", "Det är omöjligt!"),
      b("i51", "alltid", "always", "/ˈalːtɪd/", "adv.", "Hon kommer alltid i tid."),
      b("i52", "aldrig", "never", "/ˈalːdrɪɡ/", "adv.", "Jag glömmer aldrig det."),
      b("i53", "ibland", "sometimes", "/ˈiːbland/", "adv.", "Ibland regnar det."),
      b("i54", "ofta", "often", "/ˈɔfːta/", "adv.", "Vi åker dit ofta."),
      b("i55", "sällan", "rarely", "/ˈsɛlːan/", "adv.", "Jag äter sällan kött."),
      b("i56", "tillsammans", "together", "/tɪlˈsamːans/", "adv.", "Vi gör det tillsammans."),
      b("i57", "ensam", "alone, lonely", "/ˈeːnˌsɑmː/", "adj.", "Han bor ensam."),
      b("i58", "nästan", "almost", "/ˈnɛsːtan/", "adv.", "Jag är nästan klar."),
      b("i59", "precis", "exactly, just", "/prɛˈsiːs/", "adv.", "Precis vad jag menade."),
      b("i60", "äntligen", "finally", "/ˈɛnːtlɪɡɛn/", "adv.", "Äntligen helg!"),
    ],
  },
  {
    id: "advanced",
    name: "Advanced",
    description: "Idioms, nuance & natural flow",
    duration: "15 min",
    cards: [
      b("a1", "nyans", "nuance", "/nʏˈanːs/", "n.", "Det finns en viktig nyans i det han säger."),
      b("a2", "flytande", "fluent", "/ˈflyːtande/", "adj.", "Hon pratar flytande svenska."),
      b("a3", "vardaglig", "colloquial, everyday", "/ˈvɑːɖaɡliːɡ/", "adj.", "Det är ett vardagligt uttryck."),
      b("a4", "betoning", "emphasis, stress", "/bɛˈtoːnɪŋ/", "n.", "Betoningen ligger på första stavelsen."),
      b("a5", "kontext", "context", "/kɔnˈtɛkst/", "n.", "Man måste förstå kontexten."),
      b("a6", "formell", "formal", "/fɔrˈmɛl/", "adj.", "Ett formellt brev."),
      b("a7", "Det var länge sedan", "It's been a long time", "/deː var ˈlɛnːɛ ˈseːdan/", "phrase", "Det var länge sedan vi sågs."),
      b("a8", "borta bra men hemma bäst", "away is good, but home is best", "/ˈbɔrːta braː mɛn ˈhɛmːa bɛst/", "idiom", "Resan var fin, men borta bra men hemma bäst."),
      b("a9", "tala är silver, tiga är guld", "speech is silver, silence is gold", "/ˈtaːla ɛr ˈsɪlːvɛr ˈtiːɡa ɛr ɡɵld/", "idiom", "Ibland är det bättre att vara tyst."),
      b("a10", "efter regn kommer solsken", "after rain comes sunshine", "/ˈɛftɛr ˈrɛɡːn ˈkɔmɛr ˈsɔlːʂeːn/", "idiom", "Oroa dig inte — efter regn kommer solsken."),
      b("a11", "man ska inte köpa grisen i säcken", "don't buy a pig in a poke", "/man ʂaː ˈɪntɛ ˈɕøːpa ˈɡriːsɛn i ˈsɛkːɛn/", "idiom", "Läs kontraktet noga — man ska inte köpa grisen i säcken."),
      b("a12", "den som gräver en grop åt andra faller ofta själv i den", "he who digs a pit for others often falls in it himself", "/dɛn sɔm ˈɡrɛːvɛr ɛn ɡruːp oːt ˈandra ˈfalːɛr ˈɔfta ˈɧɛlv i dɛn/", "idiom", "Var snäll mot andra — den som gräver en grop åt andra faller ofta själv i den."),
      b("a13", "sitta med skägget i brevlådan", "be caught with your beard in the letterbox (be caught off guard)", "/ˈsɪtːa meːd ˈɧɛɡːɛt i ˈbreːvloːdan/", "idiom", "Nu sitter vi med skägget i brevlådan."),
      b("a14", "det är ingen ko på isen", "no cow on the ice (no worries)", "/dɛ ɛr ˈiŋɛn kuː poː ˈiːsɛn/", "idiom", "Lugna dig — det är ingen ko på isen."),
      b("a15", "gå bort", "be wasted, go to waste", "/ɡoː boːʈ/", "v. phrase", "Den goda maten får inte gå bort."),
      b("a16", "ha en gås oplockad med någon", "have a bone to pick with someone", "/haː ɛn ɡoːs ˈuːpˌplɔkːad meːd ˈnoːɡɔn/", "idiom", "Jag har en gås oplockad med dig."),
      b("a17", "kasta in handduken", "throw in the towel", "/ˈkasːta ɪn ˈhanːdʉːkɛn/", "idiom", "Ge inte upp — kasta inte in handduken än."),
      b("a18", "små grytor har också öron", "little pitchers have big ears", "/smoː ˈɡryːtʊr haːr ˈoːkˌsoː ˈøːrɔn/", "idiom", "Tänk på vad du säger — små grytor har också öron."),
      b("a19", "att göra en höna av en fjäder", "to make a mountain out of a molehill", "/at ˈjøːra ɛn ˈhøːna av ɛn ˈfjɛːdɛr/", "idiom", "Gör inte en höna av en fjäder."),
      b("a20", "sömnbrist", "sleep deprivation", "/ˈsømːnbrɪst/", "n.", "Sömnbrist påverkar koncentrationen."),
      b("a21", "egennytta", "self-interest", "/ˈeːɡɛnˌnʏtːa/", "n.", "Han handlar bara av egennytta."),
      b("a22", "medkänsla", "compassion", "/ˈmeːdˌɧɛnːsla/", "n.", "Hon visar stor medkänsla."),
      b("a23", "missnöje", "discontent", "/ˈmɪsːˌnœjɛ/", "n.", "Missnöjet växte i personalgruppen."),
      b("a24", "tillfredsställelse", "satisfaction", "/tɪlˈfrɛdsˌstɛlːɛlsɛ/", "n.", "En känsla av tillfredsställelse."),
      b("a25", "förundran", "wonder, amazement", "/fœˈrɵnːdran/", "n.", "Barnet stirrade i förundran."),
      b("a26", "vemod", "melancholy, wistfulness", "/ˈveːmuːd/", "n.", "Det var ett vemod i hennes röst."),
      b("a27", "längtan", "longing, yearning", "/ˈlɛŋːtan/", "n.", "En längtan efter sommaren."),
      b("a28", "orubblig", "unwavering, steadfast", "/ˈuːˌrɵbːlɪɡ/", "adj.", "Hans orubbliga tro på projektet."),
      b("a29", "obetydlig", "insignificant", "/ˈuːbɛˌtyːdlɪɡ/", "adj.", "Skillnaden är obetydlig."),
      b("a30", "genomskinlig", "transparent, see-through", "/ˈjeːnɔmˌɧiːnːlɪɡ/", "adj.", "Hans lögner var genomskinliga."),
      b("a31", "outtalad", "unspoken", "/ˈuːtˌtaːlad/", "adj.", "En outtalad överenskommelse."),
      b("a32", "oförglömlig", "unforgettable", "/ˈuːfœrˈɡlœmːlɪɡ/", "adj.", "En oförglömlig kväll."),
      b("a33", "framgångsrik", "successful", "/ˈframːˌɡɔŋːsriːk/", "adj.", "En framgångsrik entreprenör."),
      b("a34", "återhållsam", "restrained", "/ˈoːtɛrˌhɔlːsam/", "adj.", "En återhållsam design."),
      b("a35", "omsorgsfull", "careful, considerate", "/ˈɔmːˌsɔrːɡsˌfɵlː/", "adj.", "En omsorgsfull planering."),
      b("a36", "försiktig", "cautious", "/fœˈsɪkːtɪɡ/", "adj.", "Var försiktig på isen."),
      b("a37", "motvillig", "reluctant", "/ˈmuːtˌvɪlːiːɡ/", "adj.", "Han gick motvilligt med på det."),
      b("a38", "ivrig", "eager", "/ˈiːvrɪɡ/", "adj.", "En ivrig elev."),
      b("a39", "nogrann", "thorough, meticulous", "/ˈnuːˌɡranː/", "adj.", "Hon är mycket nogrann."),
      b("a40", "samarbetsvillig", "cooperative", "/sɑˈmarːbɛtsˌvɪlːiːɡ/", "adj.", "En samarbetsvillig kollega."),
      b("a41", "hänsynsfull", "considerate", "/ˈhɛnːsyːnsˌfɵlː/", "adj.", "Var hänsynsfull mot dina grannar."),
      b("a42", "uppmärksam", "attentive", "/ˈɵpːˌmɛrkːsam/", "adj.", "En uppmärksam lyssnare."),
      b("a43", "tålmodig", "patient", "/ˈtoːlˌmuːdɪɡ/", "adj.", "Var tålmodig, det tar tid."),
      b("a44", "äkta", "genuine, real", "/ˈɛkːta/", "adj.", "Äkta vänskap."),
      b("a45", "falsk", "false, fake", "/falsk/", "adj.", "Falska löften."),
      b("a46", "rättvis", "fair, just", "/ˈrɛtːˌviːs/", "adj.", "En rättvis dom."),
      b("a47", "orättvis", "unfair", "/ˈuːˌrɛtːˌviːs/", "adj.", "Det känns orättvist."),
      b("a48", "ömsesidig", "mutual", "/ˈœmːsɛˌsiːdɪɡ/", "adj.", "En ömsesidig respekt."),
      b("a49", "avgörande", "decisive, crucial", "/ˈavːˌjøːrandɛ/", "adj.", "Ett avgörande ögonblick."),
      b("a50", "meningsfull", "meaningful", "/ˈmeːnɪŋsˌfɵlː/", "adj.", "Ett meningsfullt samtal."),
      b("a51", "meningslös", "meaningless", "/ˈmeːnɪŋsˌløːs/", "adj.", "Det känns meningslöst."),
      b("a52", "pålitlig", "reliable", "/ˈpoːˌliːtlɪɡ/", "adj.", "En pålitlig vän."),
      b("a53", "opålitlig", "unreliable", "/ˈuːpoːˌliːtlɪɡ/", "adj.", "Bussen är opålitlig."),
      b("a54", "stolt", "proud", "/stɔlt/", "adj.", "Jag är så stolt över dig."),
      b("a55", "ödmjuk", "humble", "/ˈøːdˌmjʉːk/", "adj.", "En ödmjuk attityd."),
      b("a56", "nyfiken", "curious", "/ˈnyːˌfiːkɛn/", "adj.", "Barn är nyfikna."),
      b("a57", "likgiltig", "indifferent", "/ˈliːkˌjɪlːtɪɡ/", "adj.", "Han var likgiltig inför kritiken."),
      b("a58", "tacksam", "grateful", "/ˈtakːˌsɑmː/", "adj.", "Jag är tacksam för din hjälp."),
      b("a59", "avundsjuk", "envious, jealous", "/ˈaːvɵnːdˌɧʉːk/", "adj.", "Hon var avundsjuk på systern."),
      b("a60", "överväldigande", "overwhelming", "/ˈøːvɛrˌvɛlːdɪɡandɛ/", "adj.", "Responsen var överväldigande."),
    ],
  },
];
