export type Flashcard = {
  id: string;
  swedish: string;
  english: string;
  pronunciation?: string;
  partOfSpeech?: string;
  example?: string;
};

export type Level = {
  id: string;
  name: string;
  description: string;
  duration: string;
  cards: Flashcard[];
};

export const levels: Level[] = [
  {
    id: "beginner",
    name: "Beginner",
    description: "Essential greetings & first words",
    duration: "8 min",
    cards: [
      {
        id: "b1",
        swedish: "hej",
        english: "hello",
        pronunciation: "/hej/",
        partOfSpeech: "interj.",
        example: "Hej! Hur mår du?",
      },
      {
        id: "b2",
        swedish: "tack",
        english: "thank you",
        pronunciation: "/tak/",
        partOfSpeech: "interj.",
        example: "Tack så mycket.",
      },
      {
        id: "b3",
        swedish: "ja",
        english: "yes",
        pronunciation: "/jaː/",
        partOfSpeech: "adv.",
        example: "Ja, det förstår jag.",
      },
      {
        id: "b4",
        swedish: "nej",
        english: "no",
        pronunciation: "/nɛj/",
        partOfSpeech: "adv.",
        example: "Nej, tack.",
      },
      {
        id: "b5",
        swedish: "vatten",
        english: "water",
        pronunciation: "/ˈvatːɛn/",
        partOfSpeech: "n.",
        example: "Ett glas vatten, tack.",
      },
      {
        id: "b6",
        swedish: "kaffe",
        english: "coffee",
        pronunciation: "/ˈkafːɛ/",
        partOfSpeech: "n.",
        example: "Jag vill ha kaffe.",
      },
      {
        id: "b7",
        swedish: "bröd",
        english: "bread",
        pronunciation: "/brøːd/",
        partOfSpeech: "n.",
        example: "Brödet är färskt.",
      },
      {
        id: "b8",
        swedish: "hus",
        english: "house",
        pronunciation: "/hʉːs/",
        partOfSpeech: "n.",
        example: "Ett litet hus i skogen.",
      },
      {
        id: "b9",
        swedish: "hund",
        english: "dog",
        pronunciation: "/hɵnd/",
        partOfSpeech: "n.",
        example: "Hunden springer i parken.",
      },
      {
        id: "b10",
        swedish: "katt",
        english: "cat",
        pronunciation: "/kat/",
        partOfSpeech: "n.",
        example: "Katten sover på soffan.",
      },
      {
        id: "b11",
        swedish: "god morgon",
        english: "good morning",
        pronunciation: "/ɡuːd ˈmɔrːjɔn/",
        partOfSpeech: "phrase",
        example: "God morgon! Sovit gott?",
      },
      {
        id: "b12",
        swedish: "hej då",
        english: "goodbye",
        pronunciation: "/hej doː/",
        partOfSpeech: "phrase",
        example: "Hej då, vi ses imorgon!",
      },
    ],
  },
  {
    id: "intermediate",
    name: "Intermediate",
    description: "Everyday phrases & small talk",
    duration: "10 min",
    cards: [
      {
        id: "i1",
        swedish: "stilla",
        english: "calm, still",
        pronunciation: "/ˈsɪlːa/",
        partOfSpeech: "adj.",
        example: "Sit and watch the still water settle into quiet light.",
      },
      {
        id: "i2",
        swedish: "en promenad",
        english: "a walk",
        pronunciation: "/ɛn prɔmɛˈnaːd/",
        partOfSpeech: "n. phrase",
        example: "En lång promenad i parken.",
      },
      {
        id: "i3",
        swedish: "fika",
        english: "coffee break (with something sweet)",
        pronunciation: "/ˈfiːka/",
        partOfSpeech: "n.",
        example: "Ska vi ta en fika?",
      },
      {
        id: "i4",
        swedish: "lagom",
        english: "just right, not too much or too little",
        pronunciation: "/ˈlaːɡɔm/",
        partOfSpeech: "adj.",
        example: "Lagom är bäst.",
      },
      {
        id: "i5",
        swedish: "mysig",
        english: "cozy",
        pronunciation: "/ˈmyːsɪɡ/",
        partOfSpeech: "adj.",
        example: "Vilken mysig lägenhet!",
      },
      {
        id: "i6",
        swedish: "förstå",
        english: "understand",
        pronunciation: "/fɛrˈstoː/",
        partOfSpeech: "v.",
        example: "Jag förstår inte.",
      },
      {
        id: "i7",
        swedish: "kanske",
        english: "maybe",
        pronunciation: "/ˈkanːsɛ/",
        partOfSpeech: "adv.",
        example: "Kanske vi ses senare.",
      },
      {
        id: "i8",
        swedish: "redan",
        english: "already",
        pronunciation: "/ˈreːdan/",
        partOfSpeech: "adv.",
        example: "Han är redan här.",
      },
      {
        id: "i9",
        swedish: "vänta",
        english: "wait",
        pronunciation: "/ˈvɛnːta/",
        partOfSpeech: "v.",
        example: "Vänta ett ögonblick.",
      },
      {
        id: "i10",
        swedish: "tycker om",
        english: "like, enjoy",
        pronunciation: "/ˈtʏkɛr ɔm/",
        partOfSpeech: "v. phrase",
        example: "Jag tycker om att läsa.",
      },
      {
        id: "i11",
        swedish: "trött",
        english: "tired",
        pronunciation: "/trœt/",
        partOfSpeech: "adj.",
        example: "Jag är så trött idag.",
      },
      {
        id: "i12",
        swedish: "glad",
        english: "happy",
        pronunciation: "/ɡlaːd/",
        partOfSpeech: "adj.",
        example: "Hon är alltid glad.",
      },
    ],
  },
  {
    id: "advanced",
    name: "Advanced",
    description: "Idioms, nuance & natural flow",
    duration: "12 min",
    cards: [
      {
        id: "a1",
        swedish: "nyans",
        english: "nuance",
        pronunciation: "/nʏˈanːs/",
        partOfSpeech: "n.",
        example: "Det finns en viktig nyans i det han säger.",
      },
      {
        id: "a2",
        swedish: "flytande",
        english: "fluent",
        pronunciation: "/ˈflyːtande/",
        partOfSpeech: "adj.",
        example: "Hon pratar flytande svenska.",
      },
      {
        id: "a3",
        swedish: "vardaglig",
        english: "colloquial, everyday",
        pronunciation: "/ˈvɑːɖaɡliːɡ/",
        partOfSpeech: "adj.",
        example: "Det är ett vardagligt uttryck.",
      },
      {
        id: "a4",
        swedish: "betoning",
        english: "emphasis, stress",
        pronunciation: "/bɛˈtoːnɪŋ/",
        partOfSpeech: "n.",
        example: "Betoningen ligger på första stavelsen.",
      },
      {
        id: "a5",
        swedish: "kontext",
        english: "context",
        pronunciation: "/kɔnˈtɛkst/",
        partOfSpeech: "n.",
        example: "Man måste förstå kontexten.",
      },
      {
        id: "a6",
        swedish: "formell",
        english: "formal",
        pronunciation: "/fɔrˈmɛl/",
        partOfSpeech: "adj.",
        example: "Ett formellt brev.",
      },
      {
        id: "a7",
        swedish: "Det var länge sedan",
        english: "It's been a long time",
        pronunciation: "/deː var ˈlɛnːɛ ˈseːdan/",
        partOfSpeech: "phrase",
        example: "Det var länge sedan vi sågs.",
      },
      {
        id: "a8",
        swedish: "borta bra men hemma bäst",
        english: "away is good, but home is best",
        pronunciation: "/ˈbɔrːta braː mɛn ˈhɛmːa bɛst/",
        partOfSpeech: "idiom",
        example: "Resan var fin, men borta bra men hemma bäst.",
      },
      {
        id: "a9",
        swedish: "tala är silver, tiga är guld",
        english: "speech is silver, silence is gold",
        pronunciation: "/ˈtaːla ɛr ˈsɪlːvɛr ˈtiːɡa ɛr ɡɵld/",
        partOfSpeech: "idiom",
        example: "Ibland är det bättre att vara tyst.",
      },
      {
        id: "a10",
        swedish: "efter regn kommer solsken",
        english: "after rain comes sunshine",
        pronunciation: "/ˈɛftɛr ˈrɛɡːn ˈkɔmɛr ˈsɔlːʂeːn/",
        partOfSpeech: "idiom",
        example: "Oroa dig inte — efter regn kommer solsken.",
      },
      {
        id: "a11",
        swedish: "man ska inte köpa grisen i säcken",
        english: "don't buy a pig in a poke",
        pronunciation: "/man ʂaː ˈɪntɛ ˈɕøːpa ˈɡriːsɛn i ˈsɛkːɛn/",
        partOfSpeech: "idiom",
        example: "Läs kontraktet noga — man ska inte köpa grisen i säcken.",
      },
      {
        id: "a12",
        swedish: "den som gräver en grop åt andra faller ofta själv i den",
        english: "he who digs a pit for others often falls in it himself",
        pronunciation: "/dɛn sɔm ˈɡrɛːvɛr ɛn ɡruːp oːt ˈandra ˈfalːɛr ˈɔfta ˈɧɛlv i dɛn/",
        partOfSpeech: "idiom",
        example: "Var snäll mot andra — den som gräver en grop åt andra faller ofta själv i den.",
      },
    ],
  },
];
